global.avatars = [
require('../Images/characters/alien.png'),
require('../Images/characters/babydragon.png'),
require('../Images/characters/centaur.png'),
require('../Images/characters/cerberus.png'),
require('../Images/characters/chimera.png'),
require('../Images/characters/curupira.png'),
require('../Images/characters/cyclops.png'),
require('../Images/characters/devil.png'),
require('../Images/characters/dinosaur.png'),
require('../Images/characters/dragon.png'),

require('../Images/characters/echidna.png'),
require('../Images/characters/elf.png'),
require('../Images/characters/fairy.png'),
require('../Images/characters/frankenstein.png'),
require('../Images/characters/genie.png'),
require('../Images/characters/ghost.png'),
require('../Images/characters/goblin.png'),
require('../Images/characters/gryphon.png'),
require('../Images/characters/hand.png'),
require('../Images/characters/harpy.png'),

require('../Images/characters/hydra.png'),
require('../Images/characters/karakasakozou.png'),
require('../Images/characters/kraken.png'),
require('../Images/characters/leprechaun.png'),
require('../Images/characters/loch-ness-monster.png'),
require('../Images/characters/madre-monte.png'),
require('../Images/characters/medusa.png'),
require('../Images/characters/mermaid.png'),
require('../Images/characters/minotaur.png'),
require('../Images/characters/mushroom.png'),

require('../Images/characters/narwhal.png'),
require('../Images/characters/pegasus.png'),
require('../Images/characters/phoenix.png'),
require('../Images/characters/pinocchio.png'),
require('../Images/characters/pirate.png'),
require('../Images/characters/robot.png'),
require('../Images/characters/satyr.png'),
require('../Images/characters/scarecrow.png'),
require('../Images/characters/tree-2.png'),
require('../Images/characters/tree.png'),

require('../Images/characters/troll.png'),
require('../Images/characters/unicorn.png'),
require('../Images/characters/valkyrie.png'),
require('../Images/characters/vampire.png'),
require('../Images/characters/werewolf.png'),
require('../Images/characters/witch.png'),
require('../Images/characters/wizard.png'),
require('../Images/characters/woodcutter.png'),
require('../Images/characters/yeti.png'),
require('../Images/characters/zombie.png'),
]
